"""Run public-safe EDA, portfolio summaries, and a small ML comparison."""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
REPORT_DIR = ROOT / "reports" / "python"

FEATURE_COLUMNS = [
    "return_lag_1",
    "return_mean_5",
    "price_vs_rolling_lag_1",
    "volume_change_lag_1",
]


def load_inputs() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Load the public demo tables generated by the SQL workflow."""
    daily = pd.read_csv(DATA_DIR / "sql_asset_daily.csv", parse_dates=["observation_date"])
    monthly_portfolio = pd.read_csv(DATA_DIR / "sql_portfolio_monthly.csv")
    monthly_asset = pd.read_csv(DATA_DIR / "sql_asset_monthly.csv")
    return daily, monthly_portfolio, monthly_asset


def validate_inputs(daily: pd.DataFrame, monthly_portfolio: pd.DataFrame) -> dict[str, int]:
    """Return bounded quality checks used by tests and the reader-facing report."""
    return {
        "duplicate_daily_keys": int(
            daily.duplicated(["observation_date", "asset_id"]).sum()
        ),
        "missing_close_prices": int(daily["close_price"].isna().sum()),
        "non_positive_close_prices": int((daily["close_price"] <= 0).sum()),
        "missing_portfolio_months": int(monthly_portfolio["month"].isna().sum()),
    }


def build_features(daily: pd.DataFrame) -> pd.DataFrame:
    """Build prior-observation features to predict the current direction."""
    frame = daily.sort_values(["asset_id", "observation_date"]).copy()
    grouped = frame.groupby("asset_id", group_keys=False)
    frame["return_lag_1"] = grouped["daily_return"].shift(1)
    frame["return_mean_5"] = grouped["daily_return"].transform(
        lambda values: values.shift(1).rolling(5).mean()
    )
    frame["price_vs_rolling_lag_1"] = grouped[
        "price_vs_rolling_average_pct"
    ].shift(1)
    frame["volume_change_lag_1"] = grouped["volume"].transform(
        lambda values: values.pct_change().shift(1)
    )
    frame["positive_direction"] = (frame["daily_return"] > 0).astype(int)
    return frame.dropna(subset=FEATURE_COLUMNS + ["daily_return"]).copy()


def evaluate_models(feature_frame: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Compare simple classifiers using a chronological holdout."""
    dates = np.array(sorted(feature_frame["observation_date"].unique()))
    cutoff = dates[int(len(dates) * 0.70)]
    train = feature_frame[feature_frame["observation_date"] < cutoff]
    test = feature_frame[feature_frame["observation_date"] >= cutoff]

    models = {
        "Majority baseline": DummyClassifier(strategy="most_frequent"),
        "Logistic regression": Pipeline(
            [
                ("scale", StandardScaler()),
                ("model", LogisticRegression(max_iter=1000, random_state=42)),
            ]
        ),
        "Random forest": RandomForestClassifier(
            n_estimators=100,
            max_depth=4,
            min_samples_leaf=5,
            random_state=42,
        ),
    }

    rows: list[dict[str, object]] = []
    fitted_forest: RandomForestClassifier | None = None
    for model_name, model in models.items():
        model.fit(train[FEATURE_COLUMNS], train["positive_direction"])
        prediction = model.predict(test[FEATURE_COLUMNS])
        rows.append(
            {
                "model": model_name,
                "split_method": "chronological 70/30 holdout",
                "train_rows": len(train),
                "test_rows": len(test),
                "accuracy": accuracy_score(test["positive_direction"], prediction),
                "balanced_accuracy": balanced_accuracy_score(
                    test["positive_direction"], prediction
                ),
                "precision": precision_score(
                    test["positive_direction"], prediction, zero_division=0
                ),
                "recall": recall_score(
                    test["positive_direction"], prediction, zero_division=0
                ),
                "f1_score": f1_score(
                    test["positive_direction"], prediction, zero_division=0
                ),
            }
        )
        if model_name == "Random forest":
            fitted_forest = model

    if fitted_forest is None:
        raise RuntimeError("Random forest model was not fitted")

    importance = pd.DataFrame(
        {
            "feature": FEATURE_COLUMNS,
            "importance": fitted_forest.feature_importances_,
        }
    ).sort_values("importance", ascending=False)
    return pd.DataFrame(rows), importance


def build_asset_profile(monthly_asset: pd.DataFrame) -> pd.DataFrame:
    """Summarize contribution and volatility at a recruiter-readable grain."""
    profile = (
        monthly_asset.groupby(["asset_id", "asset_group"], as_index=False)
        .agg(
            average_weight_pct=("average_weight_pct", "mean"),
            average_monthly_contribution_pct=("contribution_to_return_pct", "mean"),
            average_annualized_volatility_pct=("annualized_volatility_pct", "mean"),
            positive_contribution_months=(
                "contribution_to_return_pct",
                lambda values: int((values > 0).sum()),
            ),
            observed_months=("month", "nunique"),
        )
        .sort_values("average_monthly_contribution_pct", ascending=False)
    )
    profile["contribution_rank"] = profile[
        "average_monthly_contribution_pct"
    ].rank(method="dense", ascending=False).astype(int)
    return profile


def build_summary(
    daily: pd.DataFrame,
    monthly_portfolio: pd.DataFrame,
    model_results: pd.DataFrame,
    quality_checks: dict[str, int],
) -> pd.DataFrame:
    """Create a small decision-ready metrics table."""
    best_model = model_results.sort_values("balanced_accuracy", ascending=False).iloc[0]
    cost_drag = (
        monthly_portfolio["gross_return_sum_pct"]
        - monthly_portfolio["net_return_sum_pct"]
    ).mean()
    return pd.DataFrame(
        [
            {
                "metric": "daily_demo_rows",
                "value": len(daily),
                "unit": "rows",
                "interpretation": "Public synthetic asset observations",
            },
            {
                "metric": "quality_checks_failed",
                "value": sum(quality_checks.values()),
                "unit": "checks",
                "interpretation": "Zero is required before analysis",
            },
            {
                "metric": "average_monthly_cost_drag",
                "value": round(float(cost_drag), 3),
                "unit": "percentage points",
                "interpretation": "Demo difference between gross and net return sums",
            },
            {
                "metric": "best_demo_model_f1",
                "value": round(float(best_model["f1_score"]), 3),
                "unit": "score",
                "interpretation": (
                    f"{best_model['model']} on deterministic synthetic data; "
                    "not expected to generalize"
                ),
            },
        ]
    )


def save_charts(
    monthly_portfolio: pd.DataFrame,
    asset_profile: pd.DataFrame,
    model_results: pd.DataFrame,
) -> None:
    """Create three bounded charts for the notebook and portfolio page."""
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    plt.style.use("seaborn-v0_8-whitegrid")

    fig, ax = plt.subplots(figsize=(9, 4.8))
    ax.plot(
        monthly_portfolio["month"],
        monthly_portfolio["gross_return_sum_pct"],
        marker="o",
        label="Gross demo return",
    )
    ax.plot(
        monthly_portfolio["month"],
        monthly_portfolio["net_return_sum_pct"],
        marker="o",
        label="Net demo return after costs",
    )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title("Execution costs reduce the monthly demo result")
    ax.set_xlabel("Month")
    ax.set_ylabel("Sum of daily return (%)")
    ax.legend()
    fig.tight_layout()
    fig.savefig(REPORT_DIR / "monthly_gross_vs_net.png", dpi=160)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.scatter(
        asset_profile["average_annualized_volatility_pct"],
        asset_profile["average_monthly_contribution_pct"],
        s=asset_profile["average_weight_pct"] * 12,
        alpha=0.75,
    )
    for row in asset_profile.itertuples():
        ax.annotate(
            row.asset_id,
            (row.average_annualized_volatility_pct, row.average_monthly_contribution_pct),
            xytext=(5, 5),
            textcoords="offset points",
        )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title("Asset contribution must be read together with risk")
    ax.set_xlabel("Average annualized volatility (%)")
    ax.set_ylabel("Average monthly contribution (%)")
    fig.tight_layout()
    fig.savefig(REPORT_DIR / "asset_risk_contribution.png", dpi=160)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 4.8))
    ordered = model_results.sort_values("balanced_accuracy", ascending=True)
    ax.barh(ordered["model"], ordered["balanced_accuracy"], color="#377eb8")
    ax.set_xlim(0, 1)
    ax.set_title("Balanced accuracy exposes the weak majority baseline")
    ax.set_xlabel("Balanced accuracy")
    for index, value in enumerate(ordered["balanced_accuracy"]):
        ax.text(min(value + 0.02, 0.97), index, f"{value:.2f}", va="center")
    fig.tight_layout()
    fig.savefig(REPORT_DIR / "model_balanced_accuracy.png", dpi=160)
    plt.close(fig)


def run_analysis() -> dict[str, object]:
    """Execute the full public analysis and save its reusable outputs."""
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    daily, monthly_portfolio, monthly_asset = load_inputs()
    quality_checks = validate_inputs(daily, monthly_portfolio)
    if any(quality_checks.values()):
        raise ValueError(f"Input quality checks failed: {quality_checks}")

    feature_frame = build_features(daily)
    model_results, feature_importance = evaluate_models(feature_frame)
    asset_profile = build_asset_profile(monthly_asset)
    summary = build_summary(daily, monthly_portfolio, model_results, quality_checks)

    asset_profile.to_csv(DATA_DIR / "python_asset_profile.csv", index=False)
    model_results.to_csv(DATA_DIR / "python_model_evaluation.csv", index=False)
    feature_importance.to_csv(DATA_DIR / "python_feature_importance.csv", index=False)
    summary.to_csv(DATA_DIR / "python_summary_metrics.csv", index=False)
    save_charts(monthly_portfolio, asset_profile, model_results)

    return {
        "quality_checks": quality_checks,
        "summary": summary,
        "asset_profile": asset_profile,
        "model_results": model_results,
        "feature_importance": feature_importance,
    }


if __name__ == "__main__":
    output = run_analysis()
    print(output["summary"].to_string(index=False))
