"""Build and execute the reader-facing Python analysis notebook."""

from __future__ import annotations

from pathlib import Path

import nbformat
import pandas as pd
from nbclient import NotebookClient


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_PATH = ROOT / "notebooks" / "bluexprice_python_eda.ipynb"


def build_notebook() -> nbformat.NotebookNode:
    summary = pd.read_csv(ROOT / "data" / "python_summary_metrics.csv")
    models = pd.read_csv(ROOT / "data" / "python_model_evaluation.csv")
    cost_drag = float(
        summary.loc[summary["metric"] == "average_monthly_cost_drag", "value"].iloc[0]
    )
    failed_checks = int(
        summary.loc[summary["metric"] == "quality_checks_failed", "value"].iloc[0]
    )
    best = models.sort_values("balanced_accuracy", ascending=False).iloc[0]
    baseline = models.loc[models["model"] == "Majority baseline"].iloc[0]
    notebook = nbformat.v4.new_notebook()
    notebook["metadata"]["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    notebook["metadata"]["language_info"] = {"name": "python"}
    notebook["cells"] = [
        nbformat.v4.new_markdown_cell(
            "# Bluexprice — Python EDA and Model Exploration\n\n"
            "Status: In Development  \n"
            "Data: deterministic public demo data  \n"
            "Purpose: portfolio demonstration, not investment advice"
        ),
        nbformat.v4.new_markdown_cell(
            "## tl;dr\n\n"
            f"All input checks passed ({failed_checks} failures). Estimated costs "
            f"reduced the monthly demo result by an average of {cost_drag:.3f} "
            f"percentage points. {best['model']} reached F1 {best['f1_score']:.3f} "
            f"versus {baseline['f1_score']:.3f} for the majority baseline. The high "
            "score reflects deterministic synthetic patterns and should not be "
            "treated as evidence of real-market predictability or profitability."
        ),
        nbformat.v4.new_markdown_cell(
            "## Context & Methods\n\n"
            "The analysis uses outputs generated by the public SQL workflow. "
            "Models use a chronological 70/30 holdout, and all predictive "
            "features come from earlier observations.\n\n"
            "### Key assumptions\n\n"
            "- Asset names and market prices are synthetic.\n"
            "- Portfolio weights are illustrative and fixed.\n"
            "- Fees and slippage are simplified estimates.\n"
            "- ML scores test implementation and validation logic, not profitability."
        ),
        nbformat.v4.new_markdown_cell("## Data\n\n### 1. Run and validate the analysis"),
        nbformat.v4.new_code_cell(
            "from python_analysis.run_analysis import run_analysis\n"
            "results = run_analysis()\n"
            "results['quality_checks']"
        ),
        nbformat.v4.new_markdown_cell("### 2. Review the decision-ready summary"),
        nbformat.v4.new_code_cell("results['summary']"),
        nbformat.v4.new_markdown_cell("## Results\n\n### 3. Compare asset contribution and risk"),
        nbformat.v4.new_code_cell("results['asset_profile']"),
        nbformat.v4.new_code_cell(
            "from IPython.display import Image, display\n"
            "display(Image(filename='reports/python/asset_risk_contribution.png'))"
        ),
        nbformat.v4.new_markdown_cell("### 4. Compare simple models with a baseline"),
        nbformat.v4.new_code_cell("results['model_results'].round(3)"),
        nbformat.v4.new_code_cell("results['feature_importance'].round(3)"),
        nbformat.v4.new_code_cell(
            "display(Image(filename='reports/python/model_balanced_accuracy.png'))"
        ),
        nbformat.v4.new_markdown_cell("### 5. Review the effect of estimated execution costs"),
        nbformat.v4.new_code_cell(
            "display(Image(filename='reports/python/monthly_gross_vs_net.png'))"
        ),
        nbformat.v4.new_markdown_cell(
            "## Takeaways\n\n"
            "- Data-quality checks pass before the analysis is promoted.\n"
            "- Estimated execution costs reduce the demo portfolio result, so "
            "gross performance should not be presented alone.\n"
            "- Contribution and volatility should be assessed together.\n"
            "- A model is useful only if it is compared with a simple baseline "
            "on later observations. The near-perfect demo score is a warning about "
            "synthetic-data simplicity, not a performance claim.\n"
            "- The next portfolio step is to expose these sanitized summaries "
            "through Tableau Public."
        ),
    ]
    return notebook


def main() -> None:
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    notebook = build_notebook()
    client = NotebookClient(
        notebook,
        timeout=120,
        kernel_name="python3",
        resources={"metadata": {"path": str(ROOT)}},
    )
    executed = client.execute()
    nbformat.write(executed, NOTEBOOK_PATH)


if __name__ == "__main__":
    main()
